from turtle import Turtle, Screen
import turtle as q
import random

screen = Screen()
t = Turtle()
t.color('white')
t.speed('fastest')
q.colormode(255)
t.hideturtle()


class lttrs:
    def draw_bar(self):
        t.left(90)
        t.forward(150)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(150)

    def start_pos(self):
        t.penup()
        t.goto(-100, -100)
        t.fillcolor(self.random_color())
        t.begin_fill()
        t.pendown()

    def random_color(self):
        r = random.randint(0, 255)
        g = random.randint(0, 255)
        b = random.randint(0, 255)
        return (r, g, b)

    def clear_scr(self):
        t.clear()
        t.penup()
        t.home()
        t.pendown()
        screen.bgcolor('black')
        t.color('white')

    def letter_a(self):
        self.start_pos()
        t.left(75)
        t.forward(250)
        t.right(75)
        t.forward(50)
        t.right(75)
        t.forward(250)
        t.right(105)
        t.forward(30)
        t.right(75)
        t.forward(125)
        t.left(75)
        t.forward(50)
        t.left(75)
        t.forward(127)
        t.right(75)
        t.forward(38)
        t.penup()
        t.end_fill()
        t.goto(-10, 110)
        t.fillcolor('black')
        t.begin_fill()
        t.pendown()
        t.left(75)
        t.forward(60)
        t.left(105)
        t.forward(50)
        t.left(105)
        t.forward(62)
        t.left(75)
        t.forward(18)
        t.end_fill()

    def letter_b(self):
        self.start_pos()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100.00, 150.00)
        t.pendown()
        t.end_fill()
        t.left(90)
        t.begin_fill()
        t.circle(-60, 180)
        t.right(180)
        t.circle(-65, 180)
        t.right(180)
        t.circle(85, 141)
        t.penup()
        t.goto(-100.00, 30.00)
        t.pendown()
        t.setheading(0)
        t.circle(85, 180)
        t.forward(30)
        t.left(90)
        t.forward(50)
        t.end_fill()

    def letter_c(self):
        t.penup()
        t.goto(50, 125)
        t.fillcolor(self.random_color())
        t.begin_fill()
        t.pendown()
        t.left(180)
        t.circle(150, 180)
        t.left(90)
        t.forward(20)
        t.left(90)
        t.circle(-125, 180)
        t.left(90)
        t.forward(30)
        t.end_fill()

    def letter_d(self):
        self.start_pos()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100.00, 150.00)
        t.pendown()
        t.end_fill()
        t.begin_fill()
        t.left(90)
        t.circle(-125, 180)
        t.left(180)
        t.circle(140, 180)
        t.forward(30)
        t.left(90)
        t.forward(37)
        t.end_fill()

    def letter_e(self):
        self.start_pos()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100.00, 150.00)
        t.pendown()
        t.end_fill()
        t.begin_fill()
        self.draw_bar()
        t.end_fill()
        t.left(90)
        t.forward(75.33)
        t.begin_fill()
        self.draw_bar()
        t.end_fill()
        t.left(90)
        t.forward(83.33)
        t.begin_fill()
        self.draw_bar()
        t.end_fill()

    def letter_f(self):
        self.start_pos()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100.00, 150.00)
        t.pendown()
        t.end_fill()
        t.begin_fill()
        self.draw_bar()
        t.end_fill()
        t.left(90)
        t.forward(75.33)
        t.begin_fill()
        self.draw_bar()
        t.end_fill()

    def letter_g(self):
        t.penup()
        t.goto(50, 125)
        t.fillcolor(self.random_color())
        t.begin_fill()
        t.pendown()
        t.left(180)
        t.circle(150, 220)
        t.setheading(0)
        t.left(90)
        t.forward(80)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(30)
        t.right(90)
        t.forward(36)
        t.right(90)
        t.forward(60)
        t.circle(-110, 172)
        t.setheading(0)
        t.left(90)
        t.forward(33)
        t.end_fill()

    def letter_h(self):
        self.start_pos()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100, 45.5)
        t.pendown()
        t.end_fill()
        t.begin_fill()
        self.draw_bar()
        t.end_fill()
        t.penup()
        t.right(180)
        t.forward(150)
        t.pendown()
        t.right(90)
        t.begin_fill()
        t.forward(125)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(260)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(100)
        t.end_fill()

    def letter_i(self):
        self.start_pos()
        t.begin_fill()
        t.forward(230)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(100)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(100)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(230)
        t.left(90)
        t.forward(30)
        t.left(90)
        t.forward(100)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(100)
        t.left(90)
        t.forward(30)
        t.end_fill()

    def letter_j(self):
        t.penup()
        t.goto(-100.00, 180.00)
        t.pendown()
        t.begin_fill()
        t.forward(100)
        t.penup()
        t.goto(-100.00, 180.00)
        t.left(90)
        t.pendown()
        t.forward(30)
        t.right(90)
        t.forward(230)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(100)
        t.left(90)
        t.forward(250)
        t.circle(-90, 150)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.circle(60, 150)
        t.forward(250)
        t.end_fill()

    def letter_k(self):
        self.start_pos()
        t.begin_fill()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.penup()
        t.goto(-100, 45.5)
        t.pendown()
        t.left(140)
        t.forward(130)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(130)
        t.left(90)
        t.forward(150)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(150)
        t.end_fill()

    def letter_l(self):
        self.start_pos()
        t.begin_fill()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(220)
        t.left(90)
        t.forward(150)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(170)
        t.end_fill()

    def letter_m(self):
        self.start_pos()
        t.begin_fill()
        t.left(180)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(60)
        t.forward(150)
        t.left(120)
        t.forward(150)
        t.right(60)
        t.forward(30)
        t.right(90)
        t.forward(250)
        t.right(90)
        t.forward(30)
        t.right(90)
        t.forward(200)
        t.left(150)
        t.forward(150)
        t.right(120)
        t.forward(150)
        t.left(180)
        t.right(30)
        t.forward(200)
        t.end_fill()


    # EOF
